#!/usr/bin/env bash
set -euo pipefail

# setup-env.sh
# Usage: scripts/setup-env.sh [--non-interactive] [--chatwoot-url URL] [--chatwoot-account-id ID] [--user-access-token TOKEN] [--brics-url URL] [--brics-api-token TOKEN] [--redis-url URL] [--frontend-url URL]

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --chatwoot-url URL           Chatwoot base URL (e.g. https://chatwoot.agrofel.com.br)
  --chatwoot-account-id ID     Chatwoot account id
  --user-access-token TOKEN    Chatwoot user access token (used for validation)
  --brics-url URL              BRICS API URL
  --brics-api-token TOKEN      BRICS API token
  --redis-url URL              Redis URL (e.g. redis://host:6379)
  --frontend-url URL           Frontend URL
  --non-interactive            Do not prompt; require flags
  --help                      Show this help

Examples:
  $0 --non-interactive --chatwoot-url https://chatwoot.agrofel.com.br --user-access-token xyz --redis-url redis://redis:6379
EOF
}

# Default values
NONINTERACTIVE=0
CHATWOOT_URL=""
CHATWOOT_ACCOUNT_ID=""
USER_ACCESS_TOKEN=""
BRICS_URL=""
BRICS_API_TOKEN=""
REDIS_URL=""
FRONTEND_URL=""

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --chatwoot-url) CHATWOOT_URL="$2"; shift 2;;
    --chatwoot-account-id) CHATWOOT_ACCOUNT_ID="$2"; shift 2;;
    --user-access-token) USER_ACCESS_TOKEN="$2"; shift 2;;
    --brics-url) BRICS_URL="$2"; shift 2;;
    --brics-api-token) BRICS_API_TOKEN="$2"; shift 2;;
    --redis-url) REDIS_URL="$2"; shift 2;;
    --frontend-url) FRONTEND_URL="$2"; shift 2;;
    --non-interactive) NONINTERACTIVE=1; shift;;
    --help) usage; exit 0;;
    *) echo "Unknown option: $1"; usage; exit 2;;
  esac
done

prompt_if_empty() {
  local var_name="$1"; shift
  local prompt_text="$1"; shift
  if [[ -z "${!var_name:-}" ]]; then
    if [[ "$NONINTERACTIVE" -eq 1 ]]; then
      echo "Missing required variable: $var_name" >&2
      exit 2
    fi
    read -rp "$prompt_text: " val
    eval "$var_name=\"$val\""
  fi
}

prompt_if_empty CHATWOOT_URL "Chatwoot base URL (e.g. https://chatwoot.agrofel.com.br)"
prompt_if_empty USER_ACCESS_TOKEN "Chatwoot user access token (used for validation)"
# Other optional prompts
if [[ -z "${REDIS_URL:-}" && "$NONINTERACTIVE" -eq 0 ]]; then
  read -rp "Redis URL (e.g. redis://chatwoot_redis:6379) [optional]: " REDIS_URL
fi
if [[ -z "${BRICS_URL:-}" && "$NONINTERACTIVE" -eq 0 ]]; then
  read -rp "BRICS URL [optional]: " BRICS_URL
fi
if [[ -z "${BRICS_API_TOKEN:-}" && "$NONINTERACTIVE" -eq 0 ]]; then
  read -rp "BRICS API token [optional]: " BRICS_API_TOKEN
fi
if [[ -z "${FRONTEND_URL:-}" && "$NONINTERACTIVE" -eq 0 ]]; then
  read -rp "Frontend URL [optional]: " FRONTEND_URL
fi
if [[ -z "${CHATWOOT_ACCOUNT_ID:-}" && "$NONINTERACTIVE" -eq 0 ]]; then
  read -rp "Chatwoot account ID [optional]: " CHATWOOT_ACCOUNT_ID
fi

# Validate Chatwoot token
validate_chatwoot() {
  if ! command -v curl >/dev/null 2>&1; then
    echo "curl not found; cannot validate Chatwoot token" >&2
    return 1
  fi
  local url
  url="${CHATWOOT_URL%/}/api/v1/profile"
  http_code=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${USER_ACCESS_TOKEN}" "$url" || true)
  if [[ "$http_code" == "200" ]]; then
    echo "Chatwoot token validated (200)"
    return 0
  else
    echo "Chatwoot token validation failed: HTTP $http_code" >&2
    return 1
  fi
}

# Validate Redis
validate_redis() {
  if [[ -z "${REDIS_URL:-}" ]]; then
    echo "No REDIS_URL provided; skipping Redis validation"
    return 0
  fi
  if command -v redis-cli >/dev/null 2>&1; then
    if redis-cli -u "$REDIS_URL" ping >/dev/null 2>&1; then
      echo "Redis responded to PING"
      return 0
    else
      echo "Redis PING failed" >&2
      return 1
    fi
  else
    echo "redis-cli not found; skipping Redis validation" >&2
    return 0
  fi
}

# Run validations
echo "Validating Chatwoot token..."
if ! validate_chatwoot; then
  echo "Chatwoot validation failed. Aborting." >&2
  exit 3
fi

echo "Validating Redis (if provided)..."
if ! validate_redis; then
  echo "Redis validation failed. Aborting." >&2
  exit 4
fi

# Write .env and .env.example
ENV_FILE=".env"
EXAMPLE_FILE=".env.example"
cat > "$EXAMPLE_FILE" <<EOF
# Example environment for Agrofel Chatwoot Dashboard
CHATWOOT_URL=
CHATWOOT_ACCOUNT_ID=
USER_ACCESS_TOKEN=
BRICS_URL=
BRICS_API_TOKEN=
REDIS_URL=
FRONTEND_URL=
EOF

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh
CHATWOOT_URL="$CHATWOOT_URL"
CHATWOOT_ACCOUNT_ID="$CHATWOOT_ACCOUNT_ID"
USER_ACCESS_TOKEN="$USER_ACCESS_TOKEN"
BRICS_URL="$BRICS_URL"
BRICS_API_TOKEN="$BRICS_API_TOKEN"
REDIS_URL="$REDIS_URL"
FRONTEND_URL="$FRONTEND_URL"
EOF

chmod 600 "$ENV_FILE" || true

echo "Wrote $ENV_FILE and $EXAMPLE_FILE"

echo "Summary:"
echo "  CHATWOOT_URL=$CHATWOOT_URL"
echo "  CHATWOOT_ACCOUNT_ID=$CHATWOOT_ACCOUNT_ID"
echo "  REDIS_URL=${REDIS_URL:-<not set>}"
echo "  FRONTEND_URL=${FRONTEND_URL:-<not set>}"

echo "Setup complete." 
